### ISSUE TITLE
Error function

### ISSUE THREAD

**Issue by rlcostapt** [llagerlof/MyLogPHP#1]
hi,

you could create a error function that write in log and kill the script.

ex:
function errorx($value = '', $tag = self::DEFAULT_TAG) {
        self::log('ERROR', $value, $tag);
        exit;
    }

**Comment by llagerlof** [comment]
Kill the script? For what purpose? A log tool should just log messages, not change the script behaviour. Or I am missing some scenario where this could be necessary?

**Comment by rlcostapt** [comment]
I thought that was important for situations like this :

ldap_connect("#################", 636)  or $log->errorx(">>Could not connect to LDAP server<<");

When the script generates an error we want it to stop.

He was merely a suggestion. thanks anyway

**Comment by llagerlof** [comment]
I understood your point. But this could be headache to developers because they not expect a forced script exit in a log method.
In your case I think you should test for a connection error and stop the script manually, like this:

``` php
$conn_ldap = ldap_connect("#################", 636);
if (!$conn_ldap) {
    $log->error(">>Could not connect to LDAP server<<");
    die();
}
```

This way people can clearly see where the script is stopping.

Thanks!
